services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Kl3sk\MqttTransportBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'

    Kl3sk\MqttTransportBundle\Mqtt\MqttTransportFactory:
        arguments:
            $topics: '%env(MQTT_TOPICS)%'
            $clientId: '%env(MQTT_CLIENT_ID)%'
        tags: ['messenger.transport_factory']

when@dev:
    services:
        Kl3sk\MqttTransportBundle\Mqtt\MqttTransportFactory:
            arguments:
                $topics: '%env(MQTT_TOPICS)%'
                $clientId: '%env(MQTT_CLIENT_ID)%'
                $logger: "@monolog.logger"
            tags: ['messenger.transport_factory']
